### ISSUE TITLE
bug in escaping characters

### ISSUE THREAD

**Issue by z0x0z** [KINGSABRI/jwtear#7]
In header or payload if any character has to be escaped using backslash then it is not working

`jwtear jws -h '{"typ":"JWT","alg":"HS256","kid":"zzzzzzzzzz\' UNION SELECT aaa"}' -p '{"user":"admin"}' -k aaa`

<img width="938" alt="Screenshot 2020-04-27 at 1 04 43 AM" src="https://user-images.githubusercontent.com/62205196/80317727-1c678280-8823-11ea-85fb-3a16669f9c97.png">

**Comment by KINGSABRI** [comment]
This is a terminal problem, not the tool itself. If you managed to escape your terminal then the tool will take whatever is given and process it.

**Comment by z0x0z** [comment]
$ is used to escape characters

`jwtear jws -h $'{"typ":"JWT","alg":"HS256","kid":"zzzzzzzzzz\' UNION SELECT \'aaa"}' -p '{"user":"admin"}' -k aaa`
