### ISSUE TITLE
Jwtear doesnt support RS256 and public_key.pem file is not taken as key argument

### ISSUE THREAD

**Issue by z0x0z** [KINGSABRI/jwtear#8]
When I use alg as RS256 it doesn't encode with it. It goes with HS256 .. weird. 
Also if I pass public_key.pem file as argument to --key, it considers public.pem as passphrase and sign it. it is not considering public_key.pem as file contents.

<img width="1045" alt="Screenshot 2020-04-27 at 11 10 23 PM" src="https://user-images.githubusercontent.com/62205196/80403323-0ddda180-88dd-11ea-9937-f43d534feb27.png">

The signature can be verified in https://jwt.io
I put public_key as signature 

<img width="1213" alt="Screenshot 2020-04-27 at 11 24 42 PM" src="https://user-images.githubusercontent.com/62205196/80404186-6cefe600-88de-11ea-95f0-ec548bbfbd30.png">

**Comment by KINGSABRI** [comment]
Hi @z0x0z 

Thank you for reporting the issues
Can you clone the repository and test your case and let me know if you got the expected behavior? 

I need to test it before I push the gem

You can test it this way

1. clone the repo
```
git clone https://github.com/KINGSABRI/jwtear.git
cd jwtear
```

2. install dependencies 
```
bundle install 
```

3. run your test
```
bundle exec bin/jwtear s -h '{"alg": "RS256"}' -p '{"user": "admin"}' -k file.key
```
